name: Load Test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        uses: grafana/setup-k6-action@v1

      - name: Verify test file exists
        run: |
          pwd
          ls -la
          test -f ./load-test.js

      - name: Run k6 load test
        run: k6 run -e BASE_URL=https://quiz-server-ma5v.onrender.com ./load-test.js
